name: Autograde your browser

on: [push]

jobs:
  main:
    name: "Autograde your browser"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/checkout@v3
        name: "Download grader scripts"
        with:
          repository: cs4560-utah-sp24/test
          path: autograder
          ref: main
      - name: "Install dependencies"
        run: sh autograder/setup.sh
      - name: "Find exercise tests"
        run: python3 autograder/run --index gh
      - run: python3 autograder/run.py --gh --index 1
        timeout-minutes: 5
        if: ${{ always() }}
	name: ${{ env.HWPART1 }}
      - run: python3 autograder/run.py --gh --index 2
        timeout-minutes: 5
        if: ${{ always() }}
	name: ${{ env.HWPART2 }}
      - run: python3 autograder/run.py --gh --index 3
        timeout-minutes: 5
        if: ${{ always() }}
	name: ${{ env.HWPART3 }}
      - run: python3 autograder/run.py --gh --index 4
        timeout-minutes: 5
        if: ${{ always() }}
	name: ${{ env.HWPART4 }}
      - run: python3 autograder/run.py --gh --index 5
        timeout-minutes: 5
        if: ${{ always() }}
	name: ${{ env.HWPART5 }}
      - name: Generate summary
        run: python3 autograder/summarize.py > $GITHUB_STEP_SUMMARY
        if: ${{ always() }}

